# Generated by Django 4.0.2 on 2022-02-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('change_adminstatus', 'Управление adminstatus'),), 'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
    ]
